version: '3.8'

networks:
  app-tier:
    driver: bridge


services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    networks:
      - app-tier
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=test_cassandra
  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    networks:
      - app-tier
    ports:
      - 19043:9042
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=test_cassandra
  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    networks:
      - app-tier
    ports:
      - 19044:9042
    environment:
      - CASSANDRA_SEEDS=cassandra1,cassandra2,cassandra3
      - CASSANDRA_CLUSTER_NAME=test_cassandra
