version: '3.8'

networks:
  app-tier:
    driver: bridge


services:
  neo4j:
    image: neo4j:enterprise
    container_name: neo4j
    networks:
      - app-tier
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
